version: '3.7'

services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/etc/nginx/html
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    networks:
      - antidote
  api:
    container_name: api
    build:
        context: ./api
        dockerfile: dockerfile
    volumes:
        - '.:/api'
        - '/api/node_modules'
    ports:
        - '8088:8080'
    environment:
        - NODE_ENV=development
        - PORT=8080
      networks:
        - antidote
networks:
  default:
    external:
      name: antidote