version: '3.7'

services:
  # nginx: 
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     - antidote
  #   depends_on:
  #     - api
  api:
    command: 
      ['node', 'server.js']
