version: '3.7'

services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - antidote
    depends_on:
      - api
  client:
    container_name: client
    networks:
      - antidote
    build:
        context: ./client
        dockerfile: Dockerfile
    volumes: 
      - './client:/usr/src/app'
      - './client/node_modules:/usr/src/app/node_modules'
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command:
        ['npm','start']
  api:
    volumes:
      - './api:/api'
      - './api/views:/api/views'
      - '/api/node_modules'
    command: 
      ['node', 'server.js']

