version: '3.7'

services:
  nginx: 
    image: local-nginx
    container_name: nginx
    volumes: 
      - ./data/certbot/conf/live/antidote-design.net:/etc/letsencrypt/live/antidote-design.net
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - antidote
    depends_on:
      - api

  client:
    container_name: client
    networks:
      - antidote
    build:
        context: ./client
        dockerfile: Dockerfile
    volumes: 
      - './client:/usr/src/app'
      - './client/node_modules:/usr/src/app/node_modules'
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command:
        ['npm','start']
  

