version: "3.7"

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: dockerfile
    networks:
      - antidote
    ports:
      - "8080:8080"

    volumes:
      - "./api:/home/node/app/"
      - "/home/node/app/node_modules"

    environment:
      - NODE_ENV=development
      - PORT=8080
    command: ["nodemon", "server.js"]

networks:
  antidote:
    driver: "bridge"
