version: '3.7'

services:
  nginx: 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/etc/nginx/html
      - ./certs:/etc/nginx/certs
      # command: ["echo", 'antodote-design.net']
    depends_on:
      - api
  api:

    command: [ "node", "server.js" ]
    environment:
        - NODE_ENV=production
        - PORT=8080
