version: '3.7'

services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    networks:
      - antidote
  api:
    container_name: api
    build:
        context: ./api
        dockerfile: dockerfile
    ports:
        - '8088:8080'
    networks:
      - antidote

  networks:
    antidote:
          driver: "bridge"