version: '3.7'

services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    volumes: 
      - ./data/certbot/conf/live/antidote-design.net:/etc/letsencrypt/live/antidote-design.net
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/html:/etc/nginx/html
      - ./client/build:/etc/nginx/html
    ports:
      - 80:80
      - 443:443
    networks:
      - antidote
    depends_on:
      - api
  api:
    container_name: api
    build:
        context: ./api
        dockerfile: dockerfile
    networks:
        - antidote
    ports:
        - '8080:8080'
    environment: 
      PORT: 8080
    
networks:
  antidote:
        driver: "bridge"