version: '3.7'

services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/etc/nginx/html
    ports:
      - 80:80
      - 443:443
    networks:
      - antidote
    depends_on:
      - api
  api:
    container_name: api
    build:
        context: ./api
        dockerfile: dockerfile
    networks:
        - antidote
    ports:
        - '8088:8080'
    restart: unless-stopped
    
networks:
  antidote:
        driver: "bridge"
# volumes:
#   nginx-html:
#     driver: local
#     driver_opts:
#         type: none
#         device: ./nginx/html
#         o: bind

