version: '3.7'

services:
  nginx: 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/etc/nginx/html
      - ./certs:/etc/nginx/certs
    depends_on:
      - api
  api:
    volumes:
        - './api:/usr/src/app'
        - '/usr/src/app/node_modules'
    environment:
        - NODE_ENV=development
        - PORT=8080
